// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: contracts/tracking-server/proto/v1/tracking.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TrackingService_SubscribeLocation_FullMethodName = "/tracking.v1.TrackingService/SubscribeLocation"
)

// TrackingServiceClient is the client API for TrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackingServiceClient interface {
	SubscribeLocation(ctx context.Context, in *SubscribeLocationRequest, opts ...grpc.CallOption) (TrackingService_SubscribeLocationClient, error)
}

type trackingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackingServiceClient(cc grpc.ClientConnInterface) TrackingServiceClient {
	return &trackingServiceClient{cc}
}

func (c *trackingServiceClient) SubscribeLocation(ctx context.Context, in *SubscribeLocationRequest, opts ...grpc.CallOption) (TrackingService_SubscribeLocationClient, error) {
	stream, err := c.cc.NewStream(ctx, &TrackingService_ServiceDesc.Streams[0], TrackingService_SubscribeLocation_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &trackingServiceSubscribeLocationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TrackingService_SubscribeLocationClient interface {
	Recv() (*LocationUpdateResponse, error)
	grpc.ClientStream
}

type trackingServiceSubscribeLocationClient struct {
	grpc.ClientStream
}

func (x *trackingServiceSubscribeLocationClient) Recv() (*LocationUpdateResponse, error) {
	m := new(LocationUpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrackingServiceServer is the server API for TrackingService service.
// All implementations must embed UnimplementedTrackingServiceServer
// for forward compatibility
type TrackingServiceServer interface {
	SubscribeLocation(*SubscribeLocationRequest, TrackingService_SubscribeLocationServer) error
	mustEmbedUnimplementedTrackingServiceServer()
}

// UnimplementedTrackingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrackingServiceServer struct {
}

func (UnimplementedTrackingServiceServer) SubscribeLocation(*SubscribeLocationRequest, TrackingService_SubscribeLocationServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeLocation not implemented")
}
func (UnimplementedTrackingServiceServer) mustEmbedUnimplementedTrackingServiceServer() {}

// UnsafeTrackingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackingServiceServer will
// result in compilation errors.
type UnsafeTrackingServiceServer interface {
	mustEmbedUnimplementedTrackingServiceServer()
}

func RegisterTrackingServiceServer(s grpc.ServiceRegistrar, srv TrackingServiceServer) {
	s.RegisterService(&TrackingService_ServiceDesc, srv)
}

func _TrackingService_SubscribeLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeLocationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrackingServiceServer).SubscribeLocation(m, &trackingServiceSubscribeLocationServer{stream})
}

type TrackingService_SubscribeLocationServer interface {
	Send(*LocationUpdateResponse) error
	grpc.ServerStream
}

type trackingServiceSubscribeLocationServer struct {
	grpc.ServerStream
}

func (x *trackingServiceSubscribeLocationServer) Send(m *LocationUpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

// TrackingService_ServiceDesc is the grpc.ServiceDesc for TrackingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracking.v1.TrackingService",
	HandlerType: (*TrackingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeLocation",
			Handler:       _TrackingService_SubscribeLocation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "contracts/tracking-server/proto/v1/tracking.proto",
}
